services:
  aiscore-service:
    build: .
    image: xuanho17102004/aiscore-service:latest
    container_name: aiscore-service
    ports:
      - "8001:8001"
    environment:
      PORT: "8001"
      PYTHONUNBUFFERED: "1"
      MODEL_DIR_FINAL: /app/models_final
    mem_limit: 1g
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8001/api/health')",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
