"""
[DEPRECATED] — Chart generation đã được tích hợp vào train_model.py (v4.0)

File này không còn được sử dụng. Tất cả 20 biểu đồ đánh giá đã được
tích hợp trực tiếp vào train_model.py (hàm plot_all_charts()).

Để tạo biểu đồ:
  1. Chạy train_model.py trên Google Colab
  2. Charts sẽ tự xuất tại /content/drive/MyDrive/Colab Notebooks/charts/

Lịch sử:
  v3.0: generate_charts.py tạo 8 charts cho Soft Voting (XGB + RF + LGBM)
  v4.0: train_model.py tạo 20 charts cho Hybrid Stacking (5 Base + RF Meta)
"""

raise DeprecationWarning(
    "generate_charts.py is deprecated. "
    "All 20 charts are now generated by train_model.py (plot_all_charts function). "
    "Run train_model.py on Google Colab instead."
)
import pandas as pd
import xgboost as xgb
import lightgbm as lgb
import joblib
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
from sklearn.metrics import roc_curve, auc, precision_recall_curve, confusion_matrix
from sklearn.calibration import calibration_curve
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

warnings.filterwarnings("ignore")

# ── Config ──
RANDOM_STATE = 42
BASE_DIR = os.path.dirname(__file__)
MODEL_DIR = os.path.join(BASE_DIR, "models")
DOCS_DIR = os.path.join(BASE_DIR, "docs")
DATA_PATH = os.path.join(BASE_DIR, "lending_club_loan_two.csv")

os.makedirs(DOCS_DIR, exist_ok=True)

# ── Style ──
plt.rcParams.update({
    "figure.facecolor": "white",
    "axes.facecolor": "#fafafa",
    "axes.grid": True,
    "grid.alpha": 0.3,
    "font.size": 11,
    "axes.titlesize": 14,
    "axes.labelsize": 12,
})

# ── Colors ──
C_PRIMARY = "#0d9488"      # teal
C_DANGER = "#ef4444"       # red
C_GOOD = "#22c55e"         # green
C_WARN = "#f59e0b"         # amber
C_INFO = "#3b82f6"         # blue
C_PURPLE = "#8b5cf6"       # purple

# ── Load metadata ──
with open(os.path.join(MODEL_DIR, "metadata.json"), "r", encoding="utf-8") as f:
    metadata = json.load(f)

FEATURE_NAMES = metadata["feature_names"]
print(f"[charts] Features: {len(FEATURE_NAMES)}")

# ── Replicate data loading (same as train_model.py) ──
print("[charts] Loading data...")
df = pd.read_csv(DATA_PATH)
df = df[df["loan_status"].isin(["Fully Paid", "Charged Off"])].copy()
df["is_default"] = (df["loan_status"] == "Charged Off").astype(int)

# sub_grade -> credit_score
_GRADES = [f"{l}{s}" for l in "ABCDEFG" for s in range(1, 6)]
SUB_GRADE_TO_SCORE = {g: int(round(750 - 600 * i / 34)) for i, g in enumerate(_GRADES)}
df["credit_score"] = df["sub_grade"].map(SUB_GRADE_TO_SCORE)
df = df.dropna(subset=["credit_score"])
df["credit_score"] = df["credit_score"].astype(int)

# Scale USD → VNĐ
RATE = metadata["usd_to_vnd_rate"]
df["capital"] = df["loan_amnt"] * RATE
df["monthly_income"] = (df["annual_inc"] / 12) * RATE
df["monthly_pay"] = df["installment"] * RATE
df["revolving_balance"] = df["revol_bal"] * RATE
df["term_months"] = df["term"].str.extract(r"(\d+)").astype(float)

def parse_emp(val):
    if pd.isna(val): return np.nan
    val = str(val).strip()
    if "10+" in val: return 10.0
    if "< 1" in val: return 0.5
    n = pd.to_numeric(val.split()[0], errors="coerce")
    return n if not pd.isna(n) else np.nan

df["emp_length_years"] = df["emp_length"].apply(parse_emp)
df["revolving_util_percent"] = df["revol_util"]
df["active_bad_debts"] = df["pub_rec"]
df["bankruptcies"] = df["pub_rec_bankruptcies"]
df["active_loans"] = df["open_acc"]
df["total_loans_history"] = df["total_acc"]

df["emp_length_years"] = df["emp_length_years"].fillna(df["emp_length_years"].median())
df["bankruptcies"] = df["bankruptcies"].fillna(0)
df["revolving_util_percent"] = df["revolving_util_percent"].fillna(df["revolving_util_percent"].median())
df["active_bad_debts"] = df["active_bad_debts"].fillna(0)

home_map = {"RENT": 0, "OWN": 1, "MORTGAGE": 2, "OTHER": 3, "NONE": 3, "ANY": 3}
df["home_ownership_enc"] = df["home_ownership"].map(home_map).fillna(3).astype(int)

purpose_map = metadata["purpose_map"]
df["purpose_enc"] = df["purpose"].map(purpose_map).fillna(3).astype(int)

df["dti"] = df["dti"].clip(0, 100)
df["active_loans"] = df["active_loans"].clip(0, 50)
df["revolving_util_percent"] = df["revolving_util_percent"].clip(0, 150)
df["monthly_income"] = df["monthly_income"].clip(0, df["monthly_income"].quantile(0.99))

df = df[FEATURE_NAMES + ["is_default"]].dropna()

X = df[FEATURE_NAMES].values
y = df["is_default"].values

scaler = joblib.load(os.path.join(MODEL_DIR, "scaler.joblib"))
X_scaled = scaler.transform(X)

_, X_test, _, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=RANDOM_STATE, stratify=y
)

model_xgb = xgb.XGBClassifier()
model_xgb.load_model(os.path.join(MODEL_DIR, "xgb_pd_model.json"))

model_rf = joblib.load(os.path.join(MODEL_DIR, "rf_pd_model.joblib"))

model_lgbm = lgb.Booster(model_file=os.path.join(MODEL_DIR, "lgbm_pd_model.txt"))

# Individual predictions
y_prob_xgb = model_xgb.predict_proba(X_test)[:, 1]
y_prob_rf = model_rf.predict_proba(X_test)[:, 1]
y_prob_lgbm = model_lgbm.predict(X_test)  # LightGBM Booster returns proba directly

# Ensemble Soft Voting: PD = mean of 3
y_prob = (y_prob_xgb + y_prob_rf + y_prob_lgbm) / 3.0
y_pred = (y_prob >= 0.5).astype(int)

print(f"[charts] Test set: {len(y_test):,} | Default rate: {y_test.mean()*100:.2f}%")

# ══════════════════════════════════════════════
# 1. ROC Curve — All Models + Ensemble
# ══════════════════════════════════════════════
print("[charts] 1/8 ROC Curve (All Models)...")

fig, ax = plt.subplots(figsize=(9, 7))

# Individual models
for name, probs, color, ls in [
    ("XGBoost", y_prob_xgb, C_INFO, "-"),
    ("Random Forest", y_prob_rf, C_GOOD, "-"),
    ("LightGBM", y_prob_lgbm, C_PURPLE, "-"),
]:
    fpr_i, tpr_i, _ = roc_curve(y_test, probs)
    auc_i = auc(fpr_i, tpr_i)
    ax.plot(fpr_i, tpr_i, color=color, linewidth=1.5, linestyle=ls, alpha=0.7,
            label=f"{name} (AUC = {auc_i:.4f})")

# Ensemble
fpr, tpr, _ = roc_curve(y_test, y_prob)
roc_auc = auc(fpr, tpr)
ax.plot(fpr, tpr, color=C_DANGER, linewidth=2.5, label=f"Ensemble (AUC = {roc_auc:.4f})")
ax.fill_between(fpr, tpr, alpha=0.08, color=C_DANGER)

ax.plot([0, 1], [0, 1], color="#94a3b8", linestyle="--", linewidth=1, label="Random (AUC = 0.5)")
ax.set_xlabel("False Positive Rate (FPR)")
ax.set_ylabel("True Positive Rate (TPR)")
ax.set_title("ROC Curve — So sánh 3 mô hình + Ensemble")
ax.legend(loc="lower right", fontsize=10)
ax.set_xlim([0, 1])
ax.set_ylim([0, 1.02])
plt.tight_layout()
plt.savefig(os.path.join(DOCS_DIR, "roc_curve.png"), dpi=150)
plt.close()

# ══════════════════════════════════════════════
# 2. Precision-Recall Curve
# ══════════════════════════════════════════════
print("[charts] 2/8 Precision-Recall Curve...")
prec, rec, _ = precision_recall_curve(y_test, y_prob)
pr_auc = auc(rec, prec)

fig, ax = plt.subplots(figsize=(8, 6))
ax.plot(rec, prec, color=C_PURPLE, linewidth=2.5, label=f"Ensemble (PR-AUC = {pr_auc:.4f})")
ax.axhline(y=y_test.mean(), color="#94a3b8", linestyle="--", linewidth=1, label=f"Baseline = {y_test.mean():.3f}")
ax.fill_between(rec, prec, alpha=0.1, color=C_PURPLE)
ax.set_xlabel("Recall")
ax.set_ylabel("Precision")
ax.set_title("Precision-Recall Curve")
ax.legend(loc="upper right", fontsize=11)
ax.set_xlim([0, 1])
ax.set_ylim([0, 1.02])
plt.tight_layout()
plt.savefig(os.path.join(DOCS_DIR, "precision_recall_curve.png"), dpi=150)
plt.close()

# ══════════════════════════════════════════════
# 3. PD Distribution Histogram
# ══════════════════════════════════════════════
print("[charts] 3/8 PD Distribution...")
fig, ax = plt.subplots(figsize=(10, 6))
pd_paid = y_prob[y_test == 0]
pd_default = y_prob[y_test == 1]

ax.hist(pd_paid, bins=80, alpha=0.65, color=C_GOOD, label=f"Fully Paid (n={len(pd_paid):,})", density=True, edgecolor="white", linewidth=0.3)
ax.hist(pd_default, bins=80, alpha=0.65, color=C_DANGER, label=f"Charged Off (n={len(pd_default):,})", density=True, edgecolor="white", linewidth=0.3)
ax.axvline(x=y_prob.mean(), color=C_INFO, linestyle="--", linewidth=1.5, label=f"Mean PD = {y_prob.mean():.3f}")
ax.set_xlabel("Xác suất vỡ nợ (PD)")
ax.set_ylabel("Mật độ (Density)")
ax.set_title("Phân phối xác suất vỡ nợ (PD) — Paid vs Default")
ax.legend(fontsize=11)
plt.tight_layout()
plt.savefig(os.path.join(DOCS_DIR, "pd_distribution.png"), dpi=150)
plt.close()

# ══════════════════════════════════════════════
# 4. Confusion Matrix Heatmap
# ══════════════════════════════════════════════
print("[charts] 4/8 Confusion Matrix...")
cm = confusion_matrix(y_test, y_pred)
fig, ax = plt.subplots(figsize=(7, 6))
im = ax.imshow(cm, interpolation="nearest", cmap="RdYlGn_r")
ax.set_title("Confusion Matrix")
ax.set_xlabel("Dự đoán (Predicted)")
ax.set_ylabel("Thực tế (Actual)")
labels = ["Fully Paid (0)", "Charged Off (1)"]
ax.set_xticks([0, 1])
ax.set_yticks([0, 1])
ax.set_xticklabels(labels, fontsize=10)
ax.set_yticklabels(labels, fontsize=10)

for i in range(2):
    for j in range(2):
        val = cm[i, j]
        pct = val / cm.sum() * 100
        color = "white" if val > cm.max() * 0.5 else "black"
        ax.text(j, i, f"{val:,}\n({pct:.1f}%)", ha="center", va="center", fontsize=13, fontweight="bold", color=color)

fig.colorbar(im, ax=ax, shrink=0.8)
plt.tight_layout()
plt.savefig(os.path.join(DOCS_DIR, "confusion_matrix.png"), dpi=150)
plt.close()

# ══════════════════════════════════════════════
# 5. Feature Importance (Horizontal Bar)
# ══════════════════════════════════════════════
print("[charts] 5/8 Feature Importance (XGBoost — representative)...")
feat_imp = metadata["feature_importance"]
names = list(feat_imp.keys())
values = list(feat_imp.values())
# Sort ascending for horizontal bar
sorted_pairs = sorted(zip(names, values), key=lambda x: x[1])
s_names, s_values = zip(*sorted_pairs)

fig, ax = plt.subplots(figsize=(10, 7))
colors = [C_PRIMARY if v > 0.05 else C_INFO if v > 0.02 else "#94a3b8" for v in s_values]
bars = ax.barh(range(len(s_names)), s_values, color=colors, edgecolor="white", linewidth=0.5, height=0.7)
ax.set_yticks(range(len(s_names)))
ax.set_yticklabels(s_names, fontsize=10)
ax.set_xlabel("Feature Importance (Gain)")
ax.set_title("Feature Importance (XGBoost) — Tầm quan trọng đặc trưng")

for bar, v in zip(bars, s_values):
    ax.text(bar.get_width() + 0.003, bar.get_y() + bar.get_height() / 2,
            f"{v:.4f}", va="center", fontsize=9, color="#374151")

plt.tight_layout()
plt.savefig(os.path.join(DOCS_DIR, "feature_importance.png"), dpi=150)
plt.close()

# ══════════════════════════════════════════════
# 6. Calibration Curve
# ══════════════════════════════════════════════
print("[charts] 6/8 Calibration Curve...")
prob_true, prob_pred = calibration_curve(y_test, y_prob, n_bins=15, strategy="uniform")

fig, ax = plt.subplots(figsize=(8, 6))
ax.plot(prob_pred, prob_true, marker="o", color=C_DANGER, linewidth=2, markersize=6, label="Ensemble")
ax.plot([0, 1], [0, 1], color="#94a3b8", linestyle="--", linewidth=1, label="Perfectly Calibrated")
ax.fill_between(prob_pred, prob_true, prob_pred, alpha=0.15, color=C_DANGER)
ax.set_xlabel("Xác suất dự đoán trung bình (Mean Predicted PD)")
ax.set_ylabel("Tỷ lệ vỡ nợ thực tế (Fraction of Positives)")
ax.set_title("Calibration Curve — Đường cong hiệu chuẩn xác suất")
ax.legend(loc="upper left", fontsize=11)
ax.set_xlim([0, 0.7])
ax.set_ylim([0, 0.7])
plt.tight_layout()
plt.savefig(os.path.join(DOCS_DIR, "calibration_curve.png"), dpi=150)
plt.close()

# ══════════════════════════════════════════════
# 7. Score Distribution by Risk Band
# ══════════════════════════════════════════════
print("[charts] 7/8 Risk Band Distribution...")
risk_scores = np.round(y_prob * 100).astype(int)

bands = [
    ("0–10 (Rất thấp)", 0, 10, C_GOOD),
    ("11–25 (Thấp)", 11, 25, "#86efac"),
    ("26–40 (Trung bình)", 26, 40, C_WARN),
    ("41–60 (Cao)", 41, 60, "#fb923c"),
    ("61–100 (Rất cao)", 61, 100, C_DANGER),
]

band_labels = []
band_counts = []
band_default_rates = []
band_colors = []

for label, lo, hi, color in bands:
    mask = (risk_scores >= lo) & (risk_scores <= hi)
    n = mask.sum()
    dr = y_test[mask].mean() * 100 if n > 0 else 0
    band_labels.append(label)
    band_counts.append(n)
    band_default_rates.append(dr)
    band_colors.append(color)

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))

# Left: Count
bars1 = ax1.bar(range(len(band_labels)), band_counts, color=band_colors, edgecolor="white", linewidth=1)
ax1.set_xticks(range(len(band_labels)))
ax1.set_xticklabels(band_labels, rotation=20, ha="right", fontsize=9)
ax1.set_ylabel("Số lượng mẫu")
ax1.set_title("Phân bổ theo nhóm rủi ro")
ax1.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"{int(x):,}"))

for bar, c in zip(bars1, band_counts):
    ax1.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 200,
             f"{c:,}", ha="center", fontsize=9, fontweight="bold")

# Right: Default rate
bars2 = ax2.bar(range(len(band_labels)), band_default_rates, color=band_colors, edgecolor="white", linewidth=1)
ax2.set_xticks(range(len(band_labels)))
ax2.set_xticklabels(band_labels, rotation=20, ha="right", fontsize=9)
ax2.set_ylabel("Tỷ lệ vỡ nợ thực tế (%)")
ax2.set_title("Tỷ lệ vỡ nợ theo nhóm rủi ro")

for bar, dr in zip(bars2, band_default_rates):
    ax2.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.5,
             f"{dr:.1f}%", ha="center", fontsize=9, fontweight="bold")

plt.tight_layout()
plt.savefig(os.path.join(DOCS_DIR, "risk_band_distribution.png"), dpi=150)
plt.close()

# ══════════════════════════════════════════════
# 8. Model Comparison Bar Chart
# ══════════════════════════════════════════════
print("[charts] 8/8 Model Comparison...")
from sklearn.metrics import roc_auc_score, brier_score_loss, log_loss as sk_log_loss

model_names = ["XGBoost", "Random Forest", "LightGBM", "Ensemble"]
model_probs = [y_prob_xgb, y_prob_rf, y_prob_lgbm, y_prob]
model_colors = [C_INFO, C_GOOD, C_PURPLE, C_DANGER]

metric_data = {}
for mn, mp in zip(model_names, model_probs):
    mp_pred = (mp >= 0.5).astype(int)
    cm_tmp = confusion_matrix(y_test, mp_pred)
    tp = cm_tmp[1, 1] if cm_tmp.shape[0] > 1 else 0
    fn = cm_tmp[1, 0] if cm_tmp.shape[0] > 1 else 0
    fp = cm_tmp[0, 1]
    tn = cm_tmp[0, 0]
    prec_val = tp / (tp + fp) if (tp + fp) > 0 else 0
    rec_val = tp / (tp + fn) if (tp + fn) > 0 else 0
    f1_val = 2 * prec_val * rec_val / (prec_val + rec_val) if (prec_val + rec_val) > 0 else 0
    metric_data[mn] = {
        "AUC-ROC": roc_auc_score(y_test, mp),
        "Precision": prec_val,
        "Recall": rec_val,
        "F1-Score": f1_val,
        "Brier Score": brier_score_loss(y_test, mp),
    }

metrics_list = ["AUC-ROC", "Precision", "Recall", "F1-Score"]
x_pos = np.arange(len(metrics_list))
bar_width = 0.2

fig, ax = plt.subplots(figsize=(12, 7))
for i, (mn, mc) in enumerate(zip(model_names, model_colors)):
    vals = [metric_data[mn][m] for m in metrics_list]
    bars = ax.bar(x_pos + i * bar_width, vals, bar_width, label=mn, color=mc, edgecolor="white", linewidth=0.5)
    for bar, v in zip(bars, vals):
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.008,
                f"{v:.3f}", ha="center", fontsize=8, fontweight="bold")

ax.set_xticks(x_pos + bar_width * 1.5)
ax.set_xticklabels(metrics_list, fontsize=11)
ax.set_ylabel("Score")
ax.set_title("So sánh hiệu năng mô hình — Model Performance Comparison")
ax.legend(fontsize=10)
ax.set_ylim([0, 1.05])
plt.tight_layout()
plt.savefig(os.path.join(DOCS_DIR, "model_comparison.png"), dpi=150)
plt.close()

print(f"\n[charts] Done! 8 charts saved to {DOCS_DIR}/")
for f in sorted(os.listdir(DOCS_DIR)):
    if f.endswith(".png"):
        size_kb = os.path.getsize(os.path.join(DOCS_DIR, f)) / 1024
        print(f"  → {f} ({size_kb:.0f} KB)")
